=== devezhao/persist4j/src/main/resources/metadata.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Metadata DTD 1.1
-->

<!--
 主节点
-->
<!ELEMENT metadata-config (entity)+>

<!--
 default-parent			- 全局实体的默认继承
 schema-name-optimize	- 是否启用 schema 名称优化（实体 ReferencesMapping 优化为 references_mapping，字段 uniqueId 优化为 UNIQUE_ID）
-->
<!ATTLIST metadata-config
	default-parent CDATA #IMPLIED
	schema-name-optimize (true | false | 1 | 0) "false"
>

<!--
 实体定义
-->
<!ELEMENT entity (field+, index*)>
<!-- 
 实体定义的属性列表
 name					- 实体名称
 physical-name			- 物理名称
 type-code				- 实体代号，3位数字
 name-field 			- 名称字段
 parent					- 父实体
 description			- 描述
 schema-name-optimize	- 是否启用schema优化
 main                   - 所属主实体
 extra-attrs            - 扩展属性（JSON格式）
 creatable              - 可创建
 updatable              - 可更新
 queryable              - 可查询
 deletable              - 可删除
-->
<!ATTLIST entity
	name       			CDATA #REQUIRED
	physical-name   	CDATA #IMPLIED
	type-code  			CDATA #REQUIRED
	name-field 			CDATA #IMPLIED
	parent		 		CDATA #IMPLIED
	description 		CDATA #IMPLIED
	schema-name-optimize (true | false | 1 | 0) "false"
	main 		 		CDATA #IMPLIED
	extra-attrs         CDATA #IMPLIED
    creatable           (true | false | 1 | 0) "true"
	updatable           (true | false | 1 | 0) "true"
	queryable           (true | false | 1 | 0) "true"
	deletable           (true | false | 1 | 0) "true"
>

<!--
 字段定义
-->
<!ELEMENT field EMPTY>
<!--
 字段定义的属性列表
 name					- 字段名称
 type					- 字段类型
 physical-name			- 物理名称
 ref-entity				- 引用实体列表
 max-length     		- 最大长度，只支持某些字段
 cascade				- 级联模式，只支持删除级联
 auto-value				- 是否含有自动值（如在MySQL中可能存在如自动增长或当前时间），如为true，则系统会忽略填充此值
 description			- 描述
 decimal-scale			- 小数位精度
 default-value			- 默认值，由数据库完成
 extra-attrs            - 扩展属性（JSON格式）
 creatable				- 可创建
 updatable				- 可更新
 queryable              - 可查询
 nullable				- 可为空
 repeatable     		- 可重复
-->
<!ATTLIST field
	name   				CDATA #REQUIRED
	type   				(primary | reference | any-reference | reference-list | char | string | text | ntext
							| int | small-int | double | decimal | long | date | timestamp | time | bool | binary) #REQUIRED
	physical-name 		CDATA #IMPLIED
	ref-entity 			CDATA #IMPLIED
	max-length      	CDATA #IMPLIED
	cascade				(delete | remove-links | ignore) "remove-links"
	auto-value      	(true | false | 1 | 0) "false"
	description 		CDATA #IMPLIED
	decimal-scale       (1 | 2 | 3 | 4 | 5 | 6 | 7 | 8) "4"
	default-value       CDATA #IMPLIED
	extra-attrs         CDATA #IMPLIED
	creatable  			(true | false | 1 | 0) "true"
	updatable  			(true | false | 1 | 0) "true"
	queryable  			(true | false | 1 | 0) "true"
	nullable   			(true | false | 1 | 0) "true"
	repeatable 			(true | false | 1 | 0) "true"
>

<!--
索引定义（只为生成 SCHEMA 所用）
-->
<!ELEMENT index EMPTY>
<!--
 字段定义的属性列表
 type					- 索引类型
 field-list				- 字段列表
-->
<!ATTLIST index
	type   				(key | unique | fulltext) "key"
	field-list		    CDATA #REQUIRED
>

=== devezhao/persist4j/src/test/resources/metadata-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE metadata-config PUBLIC "-//persist4j/Metadata 0.3" "https://raw.githubusercontent.com/devezhao/persist4j/master/src/main/resources/metadata.dtd">
<metadata-config schema-name-optimize="true" default-parent="SystemCommon">

	<entity name="SystemCommon" type-code="000">
		<field name="commonReference" type="reference" ref-entity="TestAllType" description="引用"/>
	</entity>

	<entity name="TestAllType" type-code="100">
		<field name="tPrimary" type="primary" description="主键" />
		<field name="tReference" type="reference" ref-entity="TestAllType" description="引用"/>
		<field name="tInt" type="int"/>
		<field name="tSmallInt" type="small-int"/>
		<field name="tDouble" type="double" decimal-scale="6"/>
		<field name="tDecimal" type="decimal" decimal-scale="7" />
		<field name="tLong" type="long" auto-value="true"/>
		<field name="tDate" type="date" description="日期"/>
		<field name="tTimestamp" type="timestamp" description="日期时间" />
		<field name="tTime" type="time" description="时间" />
		<field name="tChar" type="char" description="字符"/>
		<field name="tString" type="string" description="文版"/>
		<field name="tText" type="text" description="长文本"/>
		<field name="tBool" type="bool" description="布尔"/>
		<field name="tNtext" type="ntext" description="超大文本"/>
		<field name="tBinary" type="binary" description="二进制数据"/>
		<field name="tAnyReference" type="any-reference" ref-entity="*" description="任意引用"/>
		<field name="tAnyReference2" type="any-reference" ref-entity="Test2,Test3" description="任意引用"/>
		<field name="tReferenceList" type="reference-list" ref-entity="TestAllType" description="多引用"/>
		<index type="fulltext" field-list="tText,tNtext" />
		<index field-list="tReference" />
		<index field-list="tAnyReference" type="unique" />
	</entity>
	
	<entity name="Test2" type-code="102">
		<field name="t2Primary" type="primary" description="主键" />
		<field name="t2Reference" type="reference" ref-entity="TestAllType" description="引用"/>
		<field name="t2Int" type="int"/>
	</entity>
	
	<entity name="Test3" type-code="103">
		<field name="t3Primary" type="primary" description="主键" />
		<field name="t1Reference" type="reference" ref-entity="TestAllType" description="引用"/>
		<field name="t2Reference" type="reference" ref-entity="Test2" description="引用"/>
		<field name="sum" type="double"/>
		<field name="count" type="double"/>
	</entity>
	
	<entity name="Test4" type-code="104">
		<field name="t4Primary" type="primary" />
		<field name="year" type="string"/>
		<field name="quarter" type="string" />
		<field name="month" type="string"/>
		<field name="week" type="string" />
		<field name="count" type="string"/>
	</entity>

	<entity name="MainEntity" type-code="200">
		<field name="id" type="primary"/>
		<field name="name" type="string"/>
	</entity>

	<entity name="DetailEntity1" type-code="201" main="MainEntity">
		<field name="id" type="primary"/>
		<field name="name" type="string"/>
	</entity>

	<entity name="DetailEntity2" type-code="202" main="MainEntity">
		<field name="id" type="primary"/>
		<field name="name" type="string"/>
	</entity>
	
</metadata-config>
